const colors = {
  light: {
    text: "#1F2937",
    tint: "#2563EB",
    background: "#E0F2FE",
    foreground: "#1F2937",
    card: "#FFFFFF",
    cardForeground: "#1F2937",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F9FF",
    secondaryForeground: "#1E3A8A",
    muted: "#BAE6FD",
    mutedForeground: "#64748B",
    accent: "#14B8A6",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#BAE6FD",
    input: "#BAE6FD",
    emergency: "#DC2626",
    emergencyLight: "#FEF2F2",
    teal: "#14B8A6",
    tealLight: "#F0FDFA",
    success: "#10B981",
    successLight: "#ECFDF5",
    warning: "#F59E0B",
    warningLight: "#FFFBEB",
  },
  radius: 12,
};

export default colors;
