const colors = {
  light: {
    text: "#1F2937",
    tint: "#2563EB",
    background: "#E0F2FE",
    foreground: "#1F2937",
    card: "#FFFFFF",
    cardForeground: "#1F2937",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#E0F2FE",
    secondaryForeground: "#0F2747",
    muted: "#EFF6FF",
    mutedForeground: "#64748B",
    accent: "#14B8A6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DBEAFE",
    input: "#DBEAFE",
    emergency: "#EF4444",
    emergencyLight: "#F8FAFC",
    teal: "#14B8A6",
    darkTeal: "#0D9488",
    tealLight: "#ECFDF5",
    success: "#10B981",
    successLight: "#ECFDF5",
    warning: "#F59E0B",
    warningLight: "#E0F2FE",
    darkNavy: "#0F2747",
    deepNavy: "#0B1F3A",
    purple: "#7C3AED",
    lightBlue: "#E0F2FE",
    lightTeal: "#ECFDF5",
  },
  radius: 12,
};

export default colors;
